### ISSUE TITLE
What is the Local API broker?

### ISSUE THREAD

**Issue by kisa72** [albertogeniola/Custom-Meross-Pairer#19]
Hi,

Can someone please help me with what is expected in the Meross Pairer App?
I currently have Home Assistant running in a container on a linux machine. I also have a seperate MQTT Broker running on the same machine which is integrated with Home Assistant via the Home Assistant MQTT. 

What is the 'HTTP server hostname"? I have Home Assistant running as accessable over the ip address 192.168.x.x. I put that IP address in, but that fails. I've tried googleing what a Local API broker is as mentions in the App, buy I just get references to MQTT brokers. Which in my case is the same IP address anyway, so it still doesn't work.

Then there's the Username / email and Password. I had assumed it was the login for the Home Assistant, but as the first part isn't working I can't be sure.

Any help would be much appreciated.

Thanks and regards,

Markus

**Comment by skug67** [comment]
I've got the exact same question.  Anybody who can help?

**Comment by albertogeniola** [comment]
Hi all,
The `custom meross pairer app` is used to pair the Meross devices with the `Meross Local Broker Addon for HomeAssistant`. You can find that addon [here](https://github.com/albertogeniola/ha-meross-local-broker). The server address you are supposed to input is the IP address of the Addon's web-ui. In general, you don't need to input that: the meross custom pairer app is able to automatically discover that address. 

In your case, since you are not using HomeAssistant, you are not able to install the Addon. This means you don't have a local API server to use.
